-- 0001_baseline.sql
-- AUTO-GENERATED by scripts/extract-baseline.mjs from
-- services/worker/src/lib/db.ts (initDb). Do not edit by hand.
--
-- Baseline = the current production schema, captured as idempotent DDL
-- (CREATE/ALTER ... IF NOT EXISTS). Safe to run against an existing DB
-- (no-op) and to build a fresh DB from scratch.
--
-- NOTE: CREATE TABLE statements are hoisted to the top (stable order) so the
-- baseline applies cleanly on a FRESH database. The source array in db.ts
-- interleaves some ALTERs before their CREATE (which only worked because prod
-- already had the tables). See scripts/extract-baseline.mjs.
-- Statements: 279

CREATE TABLE IF NOT EXISTS documents (
      id SERIAL PRIMARY KEY,
      document_number VARCHAR(100) UNIQUE,
      legacy_document_number VARCHAR(100),
      issue_key VARCHAR(50) NOT NULL,
      template_type VARCHAR(50) NOT NULL,
      form_data JSONB NOT NULL,
      drive_link TEXT NOT NULL,
      created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
      created_by VARCHAR(255)
    );

CREATE TABLE IF NOT EXISTS document_sequences (
      kind VARCHAR(50) NOT NULL,
      year INTEGER NOT NULL,
      current_value INTEGER DEFAULT 0,
      PRIMARY KEY (kind, year)
    );

CREATE TABLE IF NOT EXISTS vendors (
      id SERIAL PRIMARY KEY,
      vendor_code VARCHAR(50) UNIQUE NOT NULL,
      vendor_name VARCHAR(255) NOT NULL,
      trade_name VARCHAR(255),
      pen_name VARCHAR(255),
      vendor_suffix VARCHAR(50),
      entity_type VARCHAR(50),
      withholding_enabled BOOLEAN DEFAULT FALSE,
      aliases TEXT,
      address TEXT,
      phone VARCHAR(50),
      email VARCHAR(255),
      contact_department VARCHAR(100),
      contact_name VARCHAR(100),
      master_contract_ref TEXT,
      bank_info TEXT,
      bank_name TEXT,
      branch_name TEXT,
      account_type VARCHAR(50),
      account_number VARCHAR(50),
      account_holder_kana TEXT,
      is_invoice_issuer BOOLEAN DEFAULT FALSE,
      invoice_registration_number VARCHAR(50)
    );

CREATE TABLE IF NOT EXISTS vendor_addresses (
      id SERIAL PRIMARY KEY,
      vendor_id INTEGER NOT NULL REFERENCES vendors(id) ON DELETE CASCADE,
      address_label VARCHAR(100),
      postal_code VARCHAR(20),
      address TEXT NOT NULL,
      is_primary BOOLEAN DEFAULT FALSE,
      sort_order INTEGER DEFAULT 0,
      created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
    );

CREATE TABLE IF NOT EXISTS vendor_bank_accounts (
      id SERIAL PRIMARY KEY,
      vendor_id INTEGER NOT NULL REFERENCES vendors(id) ON DELETE CASCADE,
      bank_label VARCHAR(100),
      bank_name TEXT,
      branch_name TEXT,
      account_type VARCHAR(50),
      account_number VARCHAR(50),
      account_holder_kana TEXT,
      is_primary BOOLEAN DEFAULT FALSE,
      sort_order INTEGER DEFAULT 0,
      created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
    );

CREATE TABLE IF NOT EXISTS vendor_contacts (
      id SERIAL PRIMARY KEY,
      vendor_id INTEGER NOT NULL REFERENCES vendors(id) ON DELETE CASCADE,
      contact_name VARCHAR(255) NOT NULL,
      contact_department VARCHAR(255),
      title VARCHAR(100),
      email VARCHAR(255),
      phone VARCHAR(50),
      is_primary BOOLEAN DEFAULT FALSE,
      sort_order INTEGER DEFAULT 0,
      remarks TEXT,
      created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
    );

CREATE TABLE IF NOT EXISTS staff (
      id SERIAL PRIMARY KEY,
      slack_user_id VARCHAR(50) UNIQUE NOT NULL,
      staff_name VARCHAR(255) NOT NULL,
      email VARCHAR(255),
      phone VARCHAR(50),
      department VARCHAR(100),
      department_code VARCHAR(50)
    );

CREATE TABLE IF NOT EXISTS department_workflow_rules (
      id SERIAL PRIMARY KEY,
      department VARCHAR(100) UNIQUE NOT NULL,
      approver_slack_id VARCHAR(50),
      stamp_operator_slack_id VARCHAR(50),
      manager_slack_id VARCHAR(50),
      slack_channel_id VARCHAR(50),
      is_active BOOLEAN DEFAULT TRUE
    );

CREATE TABLE IF NOT EXISTS legal_requests (
      id SERIAL PRIMARY KEY,
      backlog_issue_key VARCHAR(50) UNIQUE NOT NULL,
      slack_user_id VARCHAR(50),
      contract_type VARCHAR(50),
      counterparty VARCHAR(255),
      summary TEXT,
      deadline TIMESTAMP WITH TIME ZONE,
      notes TEXT,
      created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
    );

CREATE TABLE IF NOT EXISTS delivery_events (
      id SERIAL PRIMARY KEY,
      backlog_issue_key VARCHAR(50) UNIQUE NOT NULL,
      -- Phase 23.6.5: order_items は廃止予定のため FK 制約を外す
      order_item_id INTEGER,
      delivery_no INTEGER,
      delivered_at TIMESTAMP WITH TIME ZONE,
      delivered_amount DECIMAL(15, 2),
      inspection_deadline TIMESTAMP WITH TIME ZONE,
      status VARCHAR(20) DEFAULT 'pending', -- pending, completed, overdue
      note TEXT,
      linked_asset_id INTEGER, -- Link to external_assets
      created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
    );

CREATE TABLE IF NOT EXISTS ringi_records (
      id SERIAL PRIMARY KEY,
      ringi_number VARCHAR(5) UNIQUE NOT NULL,
      title TEXT NOT NULL,
      category VARCHAR(50),
      owner_name VARCHAR(255),
      owner_department VARCHAR(100),
      approved_at DATE,
      backlog_issue_key VARCHAR(50),
      status VARCHAR(50) DEFAULT 'open',
      total_budget DECIMAL(15, 2),
      remarks TEXT,
      created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
      CONSTRAINT ringi_number_5digits CHECK (ringi_number ~ '^[0-9]{5}$')
    );

CREATE TABLE IF NOT EXISTS ringi_documents (
      ringi_id INTEGER NOT NULL REFERENCES ringi_records(id) ON DELETE CASCADE,
      document_id INTEGER NOT NULL REFERENCES documents(id) ON DELETE CASCADE,
      linked_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
      PRIMARY KEY (ringi_id, document_id)
    );

CREATE TABLE IF NOT EXISTS delivery_line_items (
      id SERIAL PRIMARY KEY,
      delivery_event_id INTEGER NOT NULL REFERENCES delivery_events(id) ON DELETE CASCADE,
      -- Phase 23.6.5: order_line_items は廃止予定のため FK 制約を外す
      order_line_item_id INTEGER,
      inspected_quantity DECIMAL(10, 4),
      acceptance_ratio DECIMAL(5, 4) DEFAULT 1.0,
      inspected_amount_ex_tax DECIMAL(15, 2),
      rejection_reason TEXT,
      created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
      UNIQUE(delivery_event_id, order_line_item_id)
    );

CREATE TABLE IF NOT EXISTS sublicensees (
      id SERIAL PRIMARY KEY,
      name TEXT NOT NULL,
      name_kana TEXT,
      category VARCHAR(50),          -- 翻訳販売-プロダクトアウト / IPコラボ-ライセンスアウト 等
      default_region TEXT,
      default_language TEXT,
      rights_holder TEXT,
      contact_email TEXT,
      contact_phone VARCHAR(50),
      remarks TEXT,
      is_active BOOLEAN DEFAULT TRUE,
      created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
    );

CREATE TABLE IF NOT EXISTS work_sublicensees (
      id SERIAL PRIMARY KEY,
      -- Phase 23.6.5: license_contracts は廃止予定のため FK 制約を外す
      -- (列自体は物理 DROP 時に capability_id と一緒に撤去)
      license_contract_id INTEGER NOT NULL,
      sublicensee_id INTEGER REFERENCES sublicensees(id) ON DELETE SET NULL,
      inline_name TEXT,
      category VARCHAR(50),
      region TEXT,
      language TEXT,
      payment_terms_label TEXT,
      mg_ag_label TEXT,
      rate_label TEXT,
      remarks TEXT,
      sort_order INTEGER DEFAULT 0,
      created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
    );

CREATE TABLE IF NOT EXISTS ledgers (
      id SERIAL PRIMARY KEY,
      ledger_code VARCHAR(40) UNIQUE NOT NULL,
      title TEXT NOT NULL,
      title_kana TEXT,
      alternative_titles TEXT[] DEFAULT '{}',
      creator_name TEXT,
      publisher_name TEXT,
      remarks TEXT,
      is_active BOOLEAN DEFAULT TRUE,
      created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
    );

CREATE TABLE IF NOT EXISTS materials (
      id SERIAL PRIMARY KEY,
      ledger_id INTEGER NOT NULL REFERENCES ledgers(id) ON DELETE CASCADE,
      material_no INTEGER NOT NULL,
      material_code VARCHAR(80) UNIQUE NOT NULL,
      material_name TEXT NOT NULL,
      material_type VARCHAR(50),
      rights_holder TEXT,
      remarks TEXT,
      is_default BOOLEAN DEFAULT FALSE,
      is_active BOOLEAN DEFAULT TRUE,
      created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
      UNIQUE(ledger_id, material_no)
    );

CREATE TABLE IF NOT EXISTS manufacturing_events (
      id SERIAL PRIMARY KEY,
      backlog_issue_key VARCHAR(50) UNIQUE NOT NULL,
      -- Phase 23.6.5: license_contracts は廃止予定のため FK 制約を外す
      license_contract_id INTEGER,
      product_name VARCHAR(255) NOT NULL,
      completion_date DATE,
      quantity INTEGER,
      msrp DECIMAL(15, 2),
      total_payment DECIMAL(15, 2),
      created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
    );

CREATE TABLE IF NOT EXISTS royalty_payments (
      id SERIAL PRIMARY KEY,
      backlog_issue_key VARCHAR(50) NOT NULL,
      manufacturing_event_id INTEGER REFERENCES manufacturing_events(id) UNIQUE,
      -- Phase 23.6.5: license_contracts は廃止予定のため FK 制約を外す
      license_contract_id INTEGER,
      payment_due_date DATE,
      reporting_deadline DATE,
      total_amount DECIMAL(15, 2),
      status VARCHAR(20) DEFAULT 'calculated', -- calculated, paid
      period VARCHAR(7) NOT NULL, -- YYYY-MM
      created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
    );

CREATE TABLE IF NOT EXISTS royalty_calculations (
      id SERIAL PRIMARY KEY,
      backlog_issue_key VARCHAR(50),               -- 計算書の Backlog issue
      -- Phase 23.6.5: license_contracts / license_financial_conditions は廃止予定のため FK 制約を外す
      -- (列自体は物理 DROP 時に capability_id と一緒に撤去予定)
      license_contract_id INTEGER,
      license_financial_condition_id INTEGER,
      manufacturing_event_id INTEGER REFERENCES manufacturing_events(id),
      calc_type VARCHAR(20),                       -- manufacturing / sales / sublicense
      unit_price DECIMAL(15, 2),                   -- 基準価格 (MSRP 等)
      quantity DECIMAL(10, 4),                     -- 製造数 (総数)
      sample_quantity DECIMAL(10, 4) DEFAULT 0,    -- サンプル数 (不課金)
      billable_quantity DECIMAL(10, 4),            -- 課金対象数 = quantity - sample
      rate_pct DECIMAL(7, 4),                      -- 適用料率 (%)
      gross_royalty_ex_tax DECIMAL(15, 2),         -- 総ロイヤリティ (税抜)
      mg_amount DECIMAL(15, 2),                    -- 適用 MG 総額 (snapshot)
      mg_consumed_before DECIMAL(15, 2),           -- 前回までの MG 消化額
      mg_consumed_this_time DECIMAL(15, 2),        -- 今回 MG 消化額
      mg_consumed_after DECIMAL(15, 2),            -- 今回後 MG 累計消化額
      mg_remaining DECIMAL(15, 2),                 -- MG 残額
      mg_fully_consumed BOOLEAN DEFAULT FALSE,
      actual_royalty_ex_tax DECIMAL(15, 2),        -- 実支払額 = gross - mg_consumed_this_time
      tax_rate INTEGER DEFAULT 10,                 -- 10 / 8
      tax_amount DECIMAL(15, 2),                   -- 切り上げ消費税
      total_payment_inc_tax DECIMAL(15, 2),
      currency VARCHAR(10) DEFAULT 'JPY',
      period VARCHAR(7),                           -- YYYY-MM
      reporting_deadline DATE,
      payment_due_date DATE,
      notes TEXT,
      created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
    );

CREATE TABLE IF NOT EXISTS external_assets (
      id SERIAL PRIMARY KEY,
      asset_number VARCHAR(100) UNIQUE,
      asset_name VARCHAR(255) NOT NULL,
      asset_type VARCHAR(50) NOT NULL, -- 'contract', 'draft', 'design', 'spec'
      counterparty VARCHAR(255),
      status VARCHAR(50) DEFAULT 'active',
      file_link TEXT,
      metadata JSONB DEFAULT '{}',
      start_date DATE,
      end_date DATE,
      backlog_issue_key VARCHAR(50),
      created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
    );

CREATE TABLE IF NOT EXISTS issue_workflows (
      id SERIAL PRIMARY KEY,
      backlog_issue_key VARCHAR(50) UNIQUE NOT NULL,
      issue_type_name VARCHAR(100),
      current_status_name VARCHAR(50),
      document_draft TEXT,
      generated_documents JSONB DEFAULT '[]',
      approval_at TIMESTAMP WITH TIME ZONE,
      stamp_at TIMESTAMP WITH TIME ZONE,
      updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
    );

CREATE TABLE IF NOT EXISTS workflow_settings (
      id SERIAL PRIMARY KEY,
      issue_type_name VARCHAR(100) UNIQUE NOT NULL,
      allowed_templates JSONB DEFAULT '[]',
      status_configs JSONB DEFAULT '{}', -- e.g. { "完了": { "auto_advance": true } }
      variable_mappings JSONB DEFAULT '{}', -- { "CONTRACT_DATE": { "source": "backlog", "field": "customField_123" } }
      next_status_id INTEGER, -- Backlog status ID to move to after generation
      document_prefix VARCHAR(50), -- Prefix for document numbering
      updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
    );

CREATE TABLE IF NOT EXISTS app_settings (
      key VARCHAR(100) PRIMARY KEY,
      value JSONB DEFAULT '{}',
      updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
    );

CREATE TABLE IF NOT EXISTS contract_purposes (
      purpose_code VARCHAR(100) PRIMARY KEY,
      purpose_group VARCHAR(100) NOT NULL,
      purpose_label TEXT NOT NULL,
      category VARCHAR(50) NOT NULL,
      required_contract_type VARCHAR(100) NOT NULL,
      default_document_type VARCHAR(100) NOT NULL,
      require_work_name BOOLEAN DEFAULT FALSE,
      require_product_name BOOLEAN DEFAULT FALSE,
      require_territory BOOLEAN DEFAULT FALSE,
      require_language BOOLEAN DEFAULT FALSE,
      high_risk_flag BOOLEAN DEFAULT FALSE,
      active BOOLEAN DEFAULT TRUE,
      sort_order INTEGER DEFAULT 999,
      created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
    );

CREATE TABLE IF NOT EXISTS contract_capabilities (
      id SERIAL PRIMARY KEY,
      vendor_id INTEGER REFERENCES vendors(id),
      external_asset_id INTEGER REFERENCES external_assets(id),
      record_type VARCHAR(50) NOT NULL DEFAULT 'master_contract', -- master_contract / license_condition / publication_condition
      contract_category VARCHAR(50) NOT NULL, -- service / license / publication
      contract_type VARCHAR(100) NOT NULL, -- service_basic / license_basic / publication_license
      contract_title TEXT NOT NULL,
      document_number VARCHAR(100),
      contract_status VARCHAR(50) DEFAULT 'executed',
      effective_date DATE,
      expiration_date DATE,
      auto_renewal BOOLEAN DEFAULT FALSE,
      source_system VARCHAR(50),
      legalon_url TEXT,
      cloudsign_url TEXT,
      drive_url TEXT,
      document_url TEXT,
      purpose_codes TEXT[] DEFAULT '{}',
      purchase_order_allowed BOOLEAN DEFAULT FALSE,
      license_condition_allowed BOOLEAN DEFAULT FALSE,
      publication_contract_allowed BOOLEAN DEFAULT FALSE,
      publication_condition_allowed BOOLEAN DEFAULT FALSE,
      condition_number VARCHAR(100),
      original_work TEXT,
      work_name TEXT,
      product_name TEXT,
      media TEXT,
      territory TEXT,
      language TEXT,
      scope TEXT,
      covered_service_categories TEXT,
      covered_works TEXT,
      covered_products TEXT,
      covered_media TEXT,
      covered_territory TEXT,
      covered_language TEXT,
      sublicense_allowed VARCHAR(100),
      overseas_allowed BOOLEAN DEFAULT FALSE,
      translation_allowed BOOLEAN DEFAULT FALSE,
      ebook_allowed BOOLEAN DEFAULT FALSE,
      merchandising_allowed BOOLEAN DEFAULT FALSE,
      video_adaptation_allowed BOOLEAN DEFAULT FALSE,
      game_adaptation_allowed BOOLEAN DEFAULT FALSE,
      risk_flags JSONB DEFAULT '{}',
      legal_review_required BOOLEAN DEFAULT FALSE,
      scope_confidence VARCHAR(20) DEFAULT 'medium',
      reason_template TEXT,
      caution_note TEXT,
      created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
    );

CREATE TABLE IF NOT EXISTS capability_financial_conditions (
      id SERIAL PRIMARY KEY,
      capability_id INTEGER NOT NULL REFERENCES contract_capabilities(id) ON DELETE CASCADE,
      condition_no INTEGER NOT NULL,            -- 1=自社製造, 2=サブライセンス, 3=プロダクトアウト
      region_language_label TEXT,               -- 例: 国内・日本語
      calc_method VARCHAR(50),                  -- ROYALTY / FIXED / SUBSCRIPTION
      rate_pct DECIMAL(7, 4),                   -- 例: 5.0000 (%)
      base_price_label TEXT,                    -- 例: 上代 (MSRP)
      calc_period VARCHAR(50),                  -- 表示ラベル (kind+close_month から自動生成可)
      calc_period_kind VARCHAR(20),             -- MANUFACTURING / MONTHLY / QUARTERLY / SEMIANNUAL / ANNUAL
      calc_period_close_month SMALLINT,         -- 1-12
      currency VARCHAR(10) DEFAULT 'JPY',
      formula_text TEXT,                        -- 例: 上代 × 5.0% × 製造数
      payment_terms TEXT,
      mg_amount DECIMAL(15, 2) DEFAULT 0,       -- MG (最低保証 floor) — Phase 22.21.95 で floor 化
      ag_amount DECIMAL(15, 2) DEFAULT 0,       -- AG (前払い保証 = 累積消化) — Phase 22.21.95 で追加
      created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
      UNIQUE(capability_id, condition_no)
    );

CREATE TABLE IF NOT EXISTS capability_line_items (
      id SERIAL PRIMARY KEY,
      capability_id INTEGER NOT NULL REFERENCES contract_capabilities(id) ON DELETE CASCADE,
      line_no INTEGER NOT NULL,
      category VARCHAR(100),
      item_name TEXT,
      spec TEXT,
      calc_method VARCHAR(50),          -- FIXED / SUBSCRIPTION / ROYALTY 等
      payment_method VARCHAR(50),
      payment_terms TEXT,
      quantity DECIMAL(15, 4),
      unit_price DECIMAL(15, 2),
      amount_ex_tax DECIMAL(15, 2),
      delivery_date DATE,
      payment_date DATE,
      -- SUBSCRIPTION 系
      cycle VARCHAR(50),
      billing_day INTEGER,
      term_start DATE,
      term_end DATE,
      created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
      UNIQUE(capability_id, line_no)
    );

CREATE TABLE IF NOT EXISTS capability_expenses (
      id SERIAL PRIMARY KEY,
      capability_id INTEGER NOT NULL REFERENCES contract_capabilities(id) ON DELETE CASCADE,
      line_no INTEGER NOT NULL,
      expense_name TEXT NOT NULL,
      spec TEXT,
      spent_date DATE,
      amount_inc_tax DECIMAL(15,2),
      remarks TEXT,
      created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
      UNIQUE(capability_id, line_no)
    );

CREATE TABLE IF NOT EXISTS capability_other_fees (
      id SERIAL PRIMARY KEY,
      capability_id INTEGER NOT NULL REFERENCES contract_capabilities(id) ON DELETE CASCADE,
      line_no INTEGER NOT NULL,
      fee_name TEXT NOT NULL,
      amount DECIMAL(15,2) NOT NULL DEFAULT 0,
      remarks TEXT,
      created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
      UNIQUE(capability_id, line_no)
    );

CREATE TABLE IF NOT EXISTS contract_decision_logs (
      id SERIAL PRIMARY KEY,
      requested_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
      requester_email VARCHAR(255),
      counterparty_name_input TEXT NOT NULL,
      vendor_id INTEGER REFERENCES vendors(id),
      purpose_code VARCHAR(100),
      work_name TEXT,
      product_name TEXT,
      territory TEXT,
      language TEXT,
      additional_flags JSONB DEFAULT '{}',
      matched_capability_ids INTEGER[] DEFAULT '{}',
      result_payload JSONB DEFAULT '{}',
      created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
    );

CREATE TABLE IF NOT EXISTS document_drafts (
        id SERIAL PRIMARY KEY,
        issue_key TEXT NOT NULL,
        template_type TEXT NOT NULL,
        form_data JSONB NOT NULL DEFAULT '{}'::jsonb,
        updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        updated_by TEXT,
        UNIQUE (issue_key, template_type)
     );

ALTER TABLE documents ADD COLUMN IF NOT EXISTS document_number VARCHAR(100) UNIQUE;

ALTER TABLE documents ADD COLUMN IF NOT EXISTS legacy_document_number VARCHAR(100);

ALTER TABLE documents ADD COLUMN IF NOT EXISTS base_document_number VARCHAR(100);

ALTER TABLE documents ADD COLUMN IF NOT EXISTS revision INTEGER DEFAULT 0;

ALTER TABLE documents ADD COLUMN IF NOT EXISTS vendor_name_snapshot TEXT;

UPDATE documents
        SET base_document_number = COALESCE(base_document_number, document_number)
      WHERE base_document_number IS NULL;

CREATE INDEX IF NOT EXISTS idx_documents_base ON documents(base_document_number);

ALTER TABLE documents ADD COLUMN IF NOT EXISTS is_primary BOOLEAN DEFAULT TRUE;

ALTER TABLE documents ADD COLUMN IF NOT EXISTS superseded_by VARCHAR(100);

UPDATE documents d SET is_primary = FALSE
      WHERE is_primary IS NOT FALSE
        AND base_document_number IS NOT NULL
        AND EXISTS (
          SELECT 1 FROM documents d2
           WHERE d2.base_document_number = d.base_document_number
             AND d2.document_number <> d.document_number
             AND d2.created_at > d.created_at
        );

CREATE INDEX IF NOT EXISTS idx_documents_is_primary ON documents(is_primary);

ALTER TABLE contract_capabilities ADD COLUMN IF NOT EXISTS base_document_number VARCHAR(100);

ALTER TABLE contract_capabilities ADD COLUMN IF NOT EXISTS revision INTEGER DEFAULT 0;

ALTER TABLE contract_capabilities ADD COLUMN IF NOT EXISTS is_primary BOOLEAN DEFAULT TRUE;

ALTER TABLE contract_capabilities ADD COLUMN IF NOT EXISTS superseded_by VARCHAR(100);

UPDATE contract_capabilities cc
        SET base_document_number = d.base_document_number,
            revision             = d.revision,
            is_primary           = d.is_primary,
            superseded_by        = d.superseded_by
       FROM documents d
      WHERE cc.document_number = d.document_number
        AND (cc.base_document_number IS NULL OR cc.is_primary IS NULL);

CREATE INDEX IF NOT EXISTS idx_capabilities_is_primary ON contract_capabilities(is_primary);

CREATE INDEX IF NOT EXISTS idx_capabilities_base ON contract_capabilities(base_document_number);

ALTER TABLE documents ADD COLUMN IF NOT EXISTS lifecycle_status VARCHAR(20) DEFAULT 'final';

ALTER TABLE contract_capabilities ADD COLUMN IF NOT EXISTS lifecycle_status VARCHAR(20) DEFAULT 'final';

UPDATE documents SET lifecycle_status = 'final'
      WHERE lifecycle_status IS NULL OR lifecycle_status = '';

UPDATE contract_capabilities SET lifecycle_status = 'final'
      WHERE lifecycle_status IS NULL OR lifecycle_status = '';

CREATE INDEX IF NOT EXISTS idx_documents_lifecycle ON documents(lifecycle_status);

CREATE INDEX IF NOT EXISTS idx_capabilities_lifecycle ON contract_capabilities(lifecycle_status);

ALTER TABLE documents ADD COLUMN IF NOT EXISTS excel_issued_at TIMESTAMP WITH TIME ZONE;

ALTER TABLE documents ADD COLUMN IF NOT EXISTS excel_link TEXT;

CREATE INDEX IF NOT EXISTS idx_documents_excel_pending
       ON documents(template_type)
       WHERE excel_issued_at IS NULL;

ALTER TABLE document_sequences ADD COLUMN IF NOT EXISTS kind VARCHAR(50);

ALTER TABLE document_sequences ADD COLUMN IF NOT EXISTS year INTEGER;

ALTER TABLE vendors ADD COLUMN IF NOT EXISTS trade_name VARCHAR(255);

ALTER TABLE vendors ADD COLUMN IF NOT EXISTS pen_name VARCHAR(255);

ALTER TABLE vendors ADD COLUMN IF NOT EXISTS vendor_suffix VARCHAR(50);

ALTER TABLE vendors ADD COLUMN IF NOT EXISTS entity_type VARCHAR(50);

ALTER TABLE vendors ADD COLUMN IF NOT EXISTS withholding_enabled BOOLEAN DEFAULT FALSE;

ALTER TABLE vendors ADD COLUMN IF NOT EXISTS aliases TEXT;

ALTER TABLE vendors ADD COLUMN IF NOT EXISTS corporate_number VARCHAR(20);

ALTER TABLE vendors ADD COLUMN IF NOT EXISTS phone VARCHAR(50);

ALTER TABLE vendors ADD COLUMN IF NOT EXISTS payment_terms TEXT;

ALTER TABLE vendors ADD COLUMN IF NOT EXISTS main_business TEXT;

ALTER TABLE vendors ADD COLUMN IF NOT EXISTS transaction_category VARCHAR(100);

ALTER TABLE vendors ADD COLUMN IF NOT EXISTS capital_yen BIGINT;

ALTER TABLE vendors ADD COLUMN IF NOT EXISTS employee_count INTEGER;

ALTER TABLE vendors ADD COLUMN IF NOT EXISTS subcontract_act_applicable BOOLEAN DEFAULT FALSE;

ALTER TABLE vendors ADD COLUMN IF NOT EXISTS rating VARCHAR(100);

ALTER TABLE vendors ADD COLUMN IF NOT EXISTS antisocial_check_result VARCHAR(100);

ALTER TABLE vendors ADD COLUMN IF NOT EXISTS master_updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE vendors ADD COLUMN IF NOT EXISTS contact_department VARCHAR(100);

ALTER TABLE vendors ADD COLUMN IF NOT EXISTS contact_name VARCHAR(100);

ALTER TABLE vendors ADD COLUMN IF NOT EXISTS master_contract_ref TEXT;

ALTER TABLE vendors ADD COLUMN IF NOT EXISTS bank_info TEXT;

ALTER TABLE vendors ADD COLUMN IF NOT EXISTS branch_name TEXT;

ALTER TABLE vendors ADD COLUMN IF NOT EXISTS account_type VARCHAR(50);

ALTER TABLE vendors ADD COLUMN IF NOT EXISTS account_number VARCHAR(50);

ALTER TABLE vendors ADD COLUMN IF NOT EXISTS account_holder_kana TEXT;

ALTER TABLE vendors ADD COLUMN IF NOT EXISTS is_invoice_issuer BOOLEAN DEFAULT FALSE;

ALTER TABLE vendors ADD COLUMN IF NOT EXISTS bank_name TEXT;

ALTER TABLE vendors ADD COLUMN IF NOT EXISTS invoice_registration_number VARCHAR(50);

CREATE INDEX IF NOT EXISTS idx_vendor_addresses_vendor ON vendor_addresses(vendor_id);

CREATE INDEX IF NOT EXISTS idx_vendor_addresses_primary ON vendor_addresses(vendor_id, is_primary);

INSERT INTO vendor_addresses (vendor_id, address_label, address, is_primary, sort_order)
     SELECT v.id, 'primary', v.address, TRUE, 0
       FROM vendors v
      WHERE v.address IS NOT NULL
        AND v.address <> ''
        AND NOT EXISTS (
          SELECT 1 FROM vendor_addresses va WHERE va.vendor_id = v.id
        );

CREATE INDEX IF NOT EXISTS idx_vendor_bank_accounts_vendor ON vendor_bank_accounts(vendor_id);

CREATE INDEX IF NOT EXISTS idx_vendor_bank_accounts_primary ON vendor_bank_accounts(vendor_id, is_primary);

INSERT INTO vendor_bank_accounts
      (vendor_id, bank_label, bank_name, branch_name, account_type, account_number, account_holder_kana, is_primary, sort_order)
     SELECT v.id, 'primary', v.bank_name, v.branch_name, v.account_type, v.account_number, v.account_holder_kana, TRUE, 0
       FROM vendors v
      WHERE (COALESCE(v.bank_name, '') <> ''
          OR COALESCE(v.branch_name, '') <> ''
          OR COALESCE(v.account_number, '') <> ''
          OR COALESCE(v.account_holder_kana, '') <> '')
        AND NOT EXISTS (
          SELECT 1 FROM vendor_bank_accounts vba WHERE vba.vendor_id = v.id
        );

ALTER TABLE vendors ADD COLUMN IF NOT EXISTS vendor_rep TEXT;

CREATE INDEX IF NOT EXISTS idx_vendor_contacts_vendor ON vendor_contacts(vendor_id);

CREATE INDEX IF NOT EXISTS idx_vendor_contacts_primary ON vendor_contacts(vendor_id, is_primary);

INSERT INTO vendor_contacts (vendor_id, contact_name, contact_department, email, phone, is_primary, sort_order)
     SELECT v.id, v.contact_name, v.contact_department, v.email, v.phone, TRUE, 0
       FROM vendors v
      WHERE v.contact_name IS NOT NULL
        AND v.contact_name <> ''
        AND NOT EXISTS (
          SELECT 1 FROM vendor_contacts vc WHERE vc.vendor_id = v.id
        );

ALTER TABLE staff ADD COLUMN IF NOT EXISTS email VARCHAR(255);

ALTER TABLE staff ADD COLUMN IF NOT EXISTS phone VARCHAR(50);

ALTER TABLE staff ADD COLUMN IF NOT EXISTS app_role VARCHAR(20) DEFAULT 'viewer';

UPDATE staff
        SET app_role = 'admin'
      WHERE (app_role IS NULL OR app_role = 'viewer')
        AND department IN ('経営管理本部', '法務');

ALTER TABLE department_workflow_rules ADD COLUMN IF NOT EXISTS slack_channel_id VARCHAR(50);

ALTER TABLE legal_requests ADD COLUMN IF NOT EXISTS merged_into_issue_key VARCHAR(50);

UPDATE legal_requests lr
        SET contract_type = 'purchase_order'
       FROM documents d
      WHERE d.issue_key = lr.backlog_issue_key
        AND d.template_type LIKE '%purchase_order%'
        AND (lr.contract_type IS NULL OR lr.contract_type = '');

UPDATE legal_requests lr
        SET contract_type = 'delivery_inspec'
       FROM documents d
      WHERE d.issue_key = lr.backlog_issue_key
        AND d.template_type LIKE 'inspection%'
        AND (lr.contract_type IS NULL OR lr.contract_type = '');

UPDATE legal_requests lr
        SET contract_type = 'lic_individual'
       FROM documents d
      WHERE d.issue_key = lr.backlog_issue_key
        AND d.template_type = 'individual_license_terms'
        AND (lr.contract_type IS NULL OR lr.contract_type = '');

ALTER TABLE legal_requests ADD COLUMN IF NOT EXISTS parent_issue_key VARCHAR(50);

UPDATE legal_requests
        SET parent_issue_key = substring(notes from '親: (LEGAL-[0-9]+)')
      WHERE parent_issue_key IS NULL
        AND notes ~ '親: LEGAL-[0-9]+';

CREATE INDEX IF NOT EXISTS idx_lr_parent_issue_key
        ON legal_requests (parent_issue_key)
      WHERE parent_issue_key IS NOT NULL;

ALTER TABLE delivery_events ADD COLUMN IF NOT EXISTS linked_asset_id INTEGER;

ALTER TABLE delivery_events ADD COLUMN IF NOT EXISTS last_alert_at TIMESTAMP WITH TIME ZONE;

ALTER TABLE delivery_events ADD COLUMN IF NOT EXISTS alert_count INTEGER DEFAULT 0;

CREATE INDEX IF NOT EXISTS idx_ringi_number ON ringi_records(ringi_number);

CREATE INDEX IF NOT EXISTS idx_ringi_backlog ON ringi_records(backlog_issue_key);

CREATE INDEX IF NOT EXISTS idx_ringi_status ON ringi_records(status);

ALTER TABLE ringi_records
       ADD COLUMN IF NOT EXISTS decision_type VARCHAR(20) DEFAULT 'ringi';

UPDATE ringi_records SET decision_type = 'ringi'
       WHERE decision_type IS NULL OR decision_type = '';

ALTER TABLE ringi_records DROP CONSTRAINT IF EXISTS ringi_number_5digits;

UPDATE ringi_records
        SET ringi_number = 'R-' || ringi_number
      WHERE ringi_number ~ '^[0-9]{5}$';

DO $ringi_chk$
       BEGIN
         BEGIN
           ALTER TABLE ringi_records ADD CONSTRAINT ringi_number_format
             CHECK (ringi_number ~ '^(R|B)-[0-9]{5}$');
         EXCEPTION WHEN duplicate_object THEN
           NULL;
         END;
       END
     $ringi_chk$;

CREATE INDEX IF NOT EXISTS idx_ringi_decision_type ON ringi_records(decision_type);

CREATE INDEX IF NOT EXISTS idx_ringi_documents_doc ON ringi_documents(document_id);

ALTER TABLE documents ADD COLUMN IF NOT EXISTS document_category VARCHAR(20);

CREATE INDEX IF NOT EXISTS idx_documents_category ON documents(document_category);

CREATE OR REPLACE FUNCTION lb_category_for_template(t TEXT) RETURNS VARCHAR(20) AS $$
       BEGIN
         IF t IN ('license_master','service_master','sales_master_buyer','sales_master_standard','sales_master_credit') THEN
           RETURN 'basic';
         ELSIF t = 'individual_license_terms'
            OR t LIKE 'purchase_order%'
            OR t LIKE 'intl_purchase_order%'
            OR t LIKE 'inspection_certificate%'
            OR t LIKE 'royalty_%'
            OR t LIKE 'maintenance_spec%' THEN
           RETURN 'individual';
         ELSE
           RETURN 'other';
         END IF;
       END;
     $$ LANGUAGE plpgsql IMMUTABLE;

UPDATE documents
        SET document_category = lb_category_for_template(template_type)
      WHERE document_category IS NULL OR document_category = '';

CREATE OR REPLACE FUNCTION lb_documents_set_category() RETURNS TRIGGER AS $$
       BEGIN
         IF NEW.document_category IS NULL OR NEW.document_category = '' THEN
           NEW.document_category := lb_category_for_template(NEW.template_type);
         END IF;
         RETURN NEW;
       END;
     $$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS documents_auto_category ON documents;

CREATE TRIGGER documents_auto_category
       BEFORE INSERT OR UPDATE ON documents
       FOR EACH ROW EXECUTE FUNCTION lb_documents_set_category();

UPDATE delivery_events SET delivery_no = 1 WHERE delivery_no IS NULL;

ALTER TABLE delivery_events ALTER COLUMN delivery_no SET NOT NULL;

ALTER TABLE delivery_events ALTER COLUMN delivery_no SET DEFAULT 1;

ALTER TABLE delivery_events DROP CONSTRAINT IF EXISTS delivery_events_backlog_issue_key_key;

DROP INDEX IF EXISTS delivery_events_backlog_issue_key_key;

DO $$
       BEGIN
         IF NOT EXISTS (
           SELECT 1 FROM pg_constraint
            WHERE conname = 'delivery_events_issue_no_uniq'
         ) THEN
           ALTER TABLE delivery_events
             ADD CONSTRAINT delivery_events_issue_no_uniq
             UNIQUE (backlog_issue_key, delivery_no);
         END IF;
       END$$;

CREATE INDEX IF NOT EXISTS idx_de_issue ON delivery_events(backlog_issue_key);

CREATE INDEX IF NOT EXISTS idx_dli_delivery_event ON delivery_line_items(delivery_event_id);

CREATE INDEX IF NOT EXISTS idx_dli_order_line ON delivery_line_items(order_line_item_id);

CREATE INDEX IF NOT EXISTS idx_sublicensees_active ON sublicensees(is_active);

CREATE INDEX IF NOT EXISTS idx_sublicensees_category ON sublicensees(category);

CREATE INDEX IF NOT EXISTS idx_ws_license_contract ON work_sublicensees(license_contract_id);

CREATE INDEX IF NOT EXISTS idx_ws_sublicensee ON work_sublicensees(sublicensee_id);

ALTER TABLE work_sublicensees ADD COLUMN IF NOT EXISTS contract_date DATE;

ALTER TABLE work_sublicensees ADD COLUMN IF NOT EXISTS work_id VARCHAR(120);

CREATE INDEX IF NOT EXISTS idx_ws_work_id ON work_sublicensees(work_id);

CREATE INDEX IF NOT EXISTS idx_ledgers_active ON ledgers(is_active);

CREATE INDEX IF NOT EXISTS idx_ledgers_title_kana ON ledgers(title_kana);

ALTER TABLE ledgers ADD COLUMN IF NOT EXISTS default_rights_holder TEXT;

ALTER TABLE ledgers ADD COLUMN IF NOT EXISTS default_credit_display TEXT;

ALTER TABLE ledgers ADD COLUMN IF NOT EXISTS default_work_supplement TEXT;

ALTER TABLE ledgers ADD COLUMN IF NOT EXISTS default_approval_target TEXT;

ALTER TABLE ledgers ADD COLUMN IF NOT EXISTS default_approval_timing TEXT;

ALTER TABLE ledgers ADD COLUMN IF NOT EXISTS division TEXT[];

UPDATE ledgers SET division = ARRAY['BDG'] WHERE division IS NULL;

CREATE INDEX IF NOT EXISTS idx_ledgers_division ON ledgers USING GIN (division);

CREATE INDEX IF NOT EXISTS idx_materials_ledger ON materials(ledger_id);

ALTER TABLE manufacturing_events ADD COLUMN IF NOT EXISTS unit_price DECIMAL(15, 2);

ALTER TABLE manufacturing_events ADD COLUMN IF NOT EXISTS sample_quantity DECIMAL(10, 4) DEFAULT 0;

ALTER TABLE manufacturing_events ADD COLUMN IF NOT EXISTS billable_quantity DECIMAL(10, 4);

ALTER TABLE manufacturing_events ADD COLUMN IF NOT EXISTS edition VARCHAR(100);

UPDATE manufacturing_events
        SET unit_price = msrp
      WHERE unit_price IS NULL AND msrp IS NOT NULL;

UPDATE manufacturing_events
        SET billable_quantity = quantity
      WHERE billable_quantity IS NULL AND quantity IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_rc_license ON royalty_calculations(license_contract_id);

CREATE INDEX IF NOT EXISTS idx_rc_mfg ON royalty_calculations(manufacturing_event_id);

CREATE INDEX IF NOT EXISTS idx_rc_period ON royalty_calculations(license_contract_id, period);

ALTER TABLE royalty_calculations
       ADD COLUMN IF NOT EXISTS mg_topup_this_time DECIMAL(15, 2) DEFAULT 0;

ALTER TABLE royalty_calculations
       ADD COLUMN IF NOT EXISTS ag_amount DECIMAL(15, 2) DEFAULT 0;

ALTER TABLE royalty_calculations
       ADD COLUMN IF NOT EXISTS ag_consumed_before DECIMAL(15, 2) DEFAULT 0;

ALTER TABLE royalty_calculations
       ADD COLUMN IF NOT EXISTS ag_consumed_this_time DECIMAL(15, 2) DEFAULT 0;

ALTER TABLE royalty_calculations
       ADD COLUMN IF NOT EXISTS ag_consumed_after DECIMAL(15, 2) DEFAULT 0;

ALTER TABLE royalty_calculations
       ADD COLUMN IF NOT EXISTS ag_remaining DECIMAL(15, 2) DEFAULT 0;

ALTER TABLE royalty_calculations
       ADD COLUMN IF NOT EXISTS ag_fully_consumed BOOLEAN DEFAULT FALSE;

ALTER TABLE external_assets ADD COLUMN IF NOT EXISTS asset_number VARCHAR(100) UNIQUE;

ALTER TABLE workflow_settings ADD COLUMN IF NOT EXISTS variable_mappings JSONB DEFAULT '{}';

ALTER TABLE workflow_settings ADD COLUMN IF NOT EXISTS next_status_id INTEGER;

ALTER TABLE workflow_settings ADD COLUMN IF NOT EXISTS document_prefix VARCHAR(50);

ALTER TABLE royalty_payments ADD COLUMN IF NOT EXISTS backlog_issue_key VARCHAR(50);

ALTER TABLE contract_capabilities ADD COLUMN IF NOT EXISTS work_name TEXT;

ALTER TABLE contract_capabilities ADD COLUMN IF NOT EXISTS record_type VARCHAR(50) DEFAULT 'master_contract';

ALTER TABLE contract_capabilities ADD COLUMN IF NOT EXISTS contract_category VARCHAR(50);

ALTER TABLE contract_capabilities ADD COLUMN IF NOT EXISTS contract_type VARCHAR(100);

ALTER TABLE contract_capabilities ADD COLUMN IF NOT EXISTS contract_title TEXT;

ALTER TABLE contract_capabilities ADD COLUMN IF NOT EXISTS document_number VARCHAR(100);

ALTER TABLE contract_capabilities ADD COLUMN IF NOT EXISTS contract_status VARCHAR(50) DEFAULT 'executed';

ALTER TABLE contract_capabilities ADD COLUMN IF NOT EXISTS effective_date DATE;

ALTER TABLE contract_capabilities ADD COLUMN IF NOT EXISTS expiration_date DATE;

ALTER TABLE contract_capabilities ADD COLUMN IF NOT EXISTS auto_renewal BOOLEAN DEFAULT FALSE;

ALTER TABLE contract_capabilities ADD COLUMN IF NOT EXISTS source_system VARCHAR(50);

ALTER TABLE contract_capabilities ADD COLUMN IF NOT EXISTS legalon_url TEXT;

ALTER TABLE contract_capabilities ADD COLUMN IF NOT EXISTS cloudsign_url TEXT;

ALTER TABLE contract_capabilities ADD COLUMN IF NOT EXISTS drive_url TEXT;

ALTER TABLE contract_capabilities ADD COLUMN IF NOT EXISTS document_url TEXT;

ALTER TABLE contract_capabilities ADD COLUMN IF NOT EXISTS purpose_codes TEXT[] DEFAULT '{}';

ALTER TABLE contract_capabilities ADD COLUMN IF NOT EXISTS purchase_order_allowed BOOLEAN DEFAULT FALSE;

ALTER TABLE contract_capabilities ADD COLUMN IF NOT EXISTS license_condition_allowed BOOLEAN DEFAULT FALSE;

ALTER TABLE contract_capabilities ADD COLUMN IF NOT EXISTS publication_contract_allowed BOOLEAN DEFAULT FALSE;

ALTER TABLE contract_capabilities ADD COLUMN IF NOT EXISTS publication_condition_allowed BOOLEAN DEFAULT FALSE;

ALTER TABLE contract_capabilities ADD COLUMN IF NOT EXISTS condition_number VARCHAR(100);

ALTER TABLE contract_capabilities ADD COLUMN IF NOT EXISTS original_work TEXT;

ALTER TABLE contract_capabilities ADD COLUMN IF NOT EXISTS product_name TEXT;

ALTER TABLE contract_capabilities ADD COLUMN IF NOT EXISTS media TEXT;

ALTER TABLE contract_capabilities ADD COLUMN IF NOT EXISTS territory TEXT;

ALTER TABLE contract_capabilities ADD COLUMN IF NOT EXISTS language TEXT;

ALTER TABLE contract_capabilities ADD COLUMN IF NOT EXISTS scope TEXT;

ALTER TABLE contract_capabilities ADD COLUMN IF NOT EXISTS covered_service_categories TEXT;

ALTER TABLE contract_capabilities ADD COLUMN IF NOT EXISTS covered_works TEXT;

ALTER TABLE contract_capabilities ADD COLUMN IF NOT EXISTS covered_products TEXT;

ALTER TABLE contract_capabilities ADD COLUMN IF NOT EXISTS covered_media TEXT;

ALTER TABLE contract_capabilities ADD COLUMN IF NOT EXISTS covered_territory TEXT;

ALTER TABLE contract_capabilities ADD COLUMN IF NOT EXISTS covered_language TEXT;

ALTER TABLE contract_capabilities ADD COLUMN IF NOT EXISTS sublicense_allowed VARCHAR(100);

ALTER TABLE contract_capabilities ADD COLUMN IF NOT EXISTS overseas_allowed BOOLEAN DEFAULT FALSE;

ALTER TABLE contract_capabilities ADD COLUMN IF NOT EXISTS translation_allowed BOOLEAN DEFAULT FALSE;

ALTER TABLE contract_capabilities ADD COLUMN IF NOT EXISTS ebook_allowed BOOLEAN DEFAULT FALSE;

ALTER TABLE contract_capabilities ADD COLUMN IF NOT EXISTS merchandising_allowed BOOLEAN DEFAULT FALSE;

ALTER TABLE contract_capabilities ADD COLUMN IF NOT EXISTS video_adaptation_allowed BOOLEAN DEFAULT FALSE;

ALTER TABLE contract_capabilities ADD COLUMN IF NOT EXISTS game_adaptation_allowed BOOLEAN DEFAULT FALSE;

ALTER TABLE contract_capabilities ADD COLUMN IF NOT EXISTS risk_flags JSONB DEFAULT '{}';

ALTER TABLE contract_capabilities ADD COLUMN IF NOT EXISTS legal_review_required BOOLEAN DEFAULT FALSE;

ALTER TABLE contract_capabilities ADD COLUMN IF NOT EXISTS scope_confidence VARCHAR(20) DEFAULT 'medium';

ALTER TABLE contract_capabilities ADD COLUMN IF NOT EXISTS reason_template TEXT;

ALTER TABLE contract_capabilities ADD COLUMN IF NOT EXISTS caution_note TEXT;

ALTER TABLE contract_capabilities ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE contract_capabilities ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE contract_capabilities ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT TRUE;

CREATE INDEX IF NOT EXISTS idx_capabilities_active ON contract_capabilities(is_active);

CREATE INDEX IF NOT EXISTS idx_capabilities_vendor ON contract_capabilities(vendor_id);

CREATE INDEX IF NOT EXISTS idx_capabilities_category ON contract_capabilities(contract_category);

CREATE INDEX IF NOT EXISTS idx_capabilities_type ON contract_capabilities(contract_type);

CREATE INDEX IF NOT EXISTS idx_capabilities_record_type ON contract_capabilities(record_type);

CREATE INDEX IF NOT EXISTS idx_capabilities_purposes ON contract_capabilities USING GIN(purpose_codes);

DROP INDEX IF EXISTS idx_capabilities_doc_num;

DO $merge$
     DECLARE
       loser_count INTEGER;
     BEGIN
       CREATE TEMP TABLE _cc_winners ON COMMIT DROP AS
         SELECT DISTINCT ON (document_number)
                document_number, id AS winner_id
           FROM contract_capabilities
          WHERE document_number IS NOT NULL
          ORDER BY document_number, updated_at DESC NULLS LAST, id DESC;
       CREATE TEMP TABLE _cc_losers ON COMMIT DROP AS
         SELECT cc.id AS loser_id, w.winner_id
           FROM contract_capabilities cc
           JOIN _cc_winners w ON w.document_number = cc.document_number
          WHERE cc.id <> w.winner_id;
       SELECT COUNT(*) INTO loser_count FROM _cc_losers;
       IF loser_count > 0 THEN
         -- (3a) move financial_conditions where winner doesn't already have the condition_no
         UPDATE capability_financial_conditions cfc
            SET capability_id = l.winner_id
           FROM _cc_losers l
          WHERE cfc.capability_id = l.loser_id
            AND NOT EXISTS (
              SELECT 1 FROM capability_financial_conditions w
               WHERE w.capability_id = l.winner_id
                 AND w.condition_no = cfc.condition_no
            );
         -- (3b) delete remaining loser financial_conditions
         DELETE FROM capability_financial_conditions cfc
          USING _cc_losers l
          WHERE cfc.capability_id = l.loser_id;
         -- (4) delete loser contract_capabilities rows
         DELETE FROM contract_capabilities cc
          USING _cc_losers l
          WHERE cc.id = l.loser_id;
         RAISE NOTICE
           '[Phase 22.21.102] contract_capabilities: merged % duplicate rows by document_number (winner = latest updated_at).',
           loser_count;
       END IF;
     END
     $merge$;

CREATE UNIQUE INDEX IF NOT EXISTS contract_capabilities_doc_num_uniq
       ON contract_capabilities(document_number);

ALTER TABLE contract_capabilities ADD COLUMN IF NOT EXISTS additional_parties JSONB DEFAULT '[]'::jsonb;

CREATE INDEX IF NOT EXISTS idx_capabilities_additional_parties
       ON contract_capabilities USING GIN (additional_parties);

ALTER TABLE contract_capabilities ADD COLUMN IF NOT EXISTS renewal_notice_months INTEGER;

ALTER TABLE contract_capabilities ADD COLUMN IF NOT EXISTS alert_lead_months INTEGER;

ALTER TABLE contract_capabilities ADD COLUMN IF NOT EXISTS last_renewal_alert_at TIMESTAMP WITH TIME ZONE;

ALTER TABLE contract_capabilities ADD COLUMN IF NOT EXISTS alert_slack_channels JSONB DEFAULT '[]'::jsonb;

ALTER TABLE contract_capabilities ADD COLUMN IF NOT EXISTS alert_slack_mentions JSONB DEFAULT '[]'::jsonb;

ALTER TABLE contract_capabilities ADD COLUMN IF NOT EXISTS ledger_code VARCHAR(40);

CREATE INDEX IF NOT EXISTS idx_capabilities_ledger_code
       ON contract_capabilities (ledger_code) WHERE ledger_code IS NOT NULL;

ALTER TABLE contract_capabilities ADD COLUMN IF NOT EXISTS ledger_ref_id INTEGER;

ALTER TABLE contract_capabilities ADD COLUMN IF NOT EXISTS material_ref_id INTEGER;

CREATE INDEX IF NOT EXISTS idx_cfc_capability ON capability_financial_conditions(capability_id);

ALTER TABLE capability_financial_conditions
       ADD COLUMN IF NOT EXISTS ag_amount DECIMAL(15, 2) DEFAULT 0;

CREATE INDEX IF NOT EXISTS idx_cli_capability ON capability_line_items(capability_id);

ALTER TABLE contract_capabilities ADD COLUMN IF NOT EXISTS tax_rate INTEGER DEFAULT 10;

ALTER TABLE contract_capabilities ADD COLUMN IF NOT EXISTS amount_ex_tax DECIMAL(15,2);

ALTER TABLE contract_capabilities ADD COLUMN IF NOT EXISTS amount_inc_tax DECIMAL(15,2);

ALTER TABLE contract_capabilities ADD COLUMN IF NOT EXISTS tax_amount DECIMAL(15,2);

ALTER TABLE contract_capabilities ADD COLUMN IF NOT EXISTS due_date DATE;

ALTER TABLE contract_capabilities ADD COLUMN IF NOT EXISTS issue_date_po DATE;

ALTER TABLE contract_capabilities ADD COLUMN IF NOT EXISTS legal_request_id INTEGER REFERENCES legal_requests(id);

ALTER TABLE contract_capabilities ADD COLUMN IF NOT EXISTS backlog_issue_key VARCHAR(50);

CREATE INDEX IF NOT EXISTS idx_capabilities_backlog ON contract_capabilities(backlog_issue_key) WHERE backlog_issue_key IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_capabilities_record_type_cat ON contract_capabilities(record_type, contract_category);

UPDATE contract_capabilities
        SET record_type = 'purchase_order',
            contract_category = COALESCE(contract_category, 'service'),
            updated_at = CURRENT_TIMESTAMP
      WHERE record_type = 'individual_contract'
        AND (
          contract_type = 'purchase_order'
          OR contract_type = 'intl_purchase_order'
          OR document_number LIKE 'ARC-PO-%'
          OR document_number LIKE 'ARC-IPO-%'
        );

UPDATE contract_capabilities
        SET record_type = 'delivery_record',
            contract_category = COALESCE(contract_category, 'service'),
            updated_at = CURRENT_TIMESTAMP
      WHERE record_type = 'individual_contract'
        AND (
          contract_type LIKE '%inspection%'
          OR document_number LIKE 'ARC-IC-%'
        );

ALTER TABLE capability_line_items ADD COLUMN IF NOT EXISTS inspected_amount_ex_tax DECIMAL(15,2) DEFAULT 0;

ALTER TABLE capability_line_items ADD COLUMN IF NOT EXISTS last_alert_at TIMESTAMP WITH TIME ZONE;

ALTER TABLE capability_line_items ADD COLUMN IF NOT EXISTS alert_count INTEGER DEFAULT 0;

CREATE INDEX IF NOT EXISTS idx_ce_capability ON capability_expenses(capability_id);

CREATE INDEX IF NOT EXISTS idx_cof_capability ON capability_other_fees(capability_id);

ALTER TABLE delivery_events ADD COLUMN IF NOT EXISTS capability_id INTEGER REFERENCES contract_capabilities(id);

ALTER TABLE delivery_line_items ADD COLUMN IF NOT EXISTS capability_line_item_id INTEGER REFERENCES capability_line_items(id);

CREATE INDEX IF NOT EXISTS idx_de_capability ON delivery_events(capability_id);

CREATE INDEX IF NOT EXISTS idx_dli_capability_line ON delivery_line_items(capability_line_item_id);

ALTER TABLE royalty_calculations ADD COLUMN IF NOT EXISTS capability_id INTEGER REFERENCES contract_capabilities(id);

ALTER TABLE royalty_calculations ADD COLUMN IF NOT EXISTS capability_financial_condition_id INTEGER REFERENCES capability_financial_conditions(id);

CREATE INDEX IF NOT EXISTS idx_rc_capability ON royalty_calculations(capability_id);

DO $rc_backfill$
     BEGIN
       IF to_regclass('public.license_contracts') IS NOT NULL THEN
         UPDATE royalty_calculations rc
            SET capability_id = cc.id
           FROM license_contracts lc
           JOIN contract_capabilities cc
             ON cc.document_number = COALESCE(lc.contract_number, lc.ledger_number, lc.work_id)
          WHERE rc.license_contract_id = lc.id
            AND rc.capability_id IS NULL
            AND cc.document_number IS NOT NULL;
       END IF;
     END
     $rc_backfill$;

INSERT INTO contract_purposes (purpose_code, purpose_group, purpose_label, category, required_contract_type, default_document_type, sort_order) VALUES
      ('service_general', '業務を依頼する', '制作・編集・デザイン等の業務を依頼したい', 'service', 'service_basic', 'purchase_order', 10),
      ('service_creative', '業務を依頼する', 'イラスト・原稿・DTP・校正等を依頼したい', 'service', 'service_basic', 'purchase_order', 20),
      ('service_event', '業務を依頼する', 'イベント運営・スタッフ業務を依頼したい', 'service', 'service_basic', 'purchase_order', 30),
      ('license_game', '作品・IPを利用する', '作品・ゲーム・IPをアナログゲーム化したい', 'license', 'license_basic', 'license_condition', 40),
      ('license_localize', '作品・IPを利用する', '作品を別地域・別言語で展開したい', 'license', 'license_basic', 'license_condition', 50),
      ('license_sublicense', '作品・IPを利用する', '第三者に再許諾・OEM展開したい', 'license', 'license_basic', 'license_condition', 60),
      ('publication_paper', '出版する', '紙書籍として出版したい', 'publication', 'publication_license', 'publication_contract', 70),
      ('publication_ebook', '出版する', '電子書籍として配信したい', 'publication', 'publication_license', 'publication_contract', 80),
      ('publication_translation', '出版する', '海外出版・翻訳版を出したい', 'publication', 'publication_license', 'publication_contract', 90),
      ('publication_merch', '出版する', '出版物・イラストを商品化したい', 'publication', 'publication_license', 'publication_contract', 100),
      ('publication_video_game', '出版する', '映像化・ゲーム化したい', 'publication', 'publication_license', 'legal_review', 110),
      ('mixed_service_license', '複合取引', '業務依頼と権利利用の両方がある', 'mixed', 'service_basic,license_basic', 'purchase_order,license_condition', 120),
      ('unknown', 'その他', 'どれに該当するかわからない', 'unknown', 'unknown', 'legal_review', 999)
    ON CONFLICT (purpose_code) DO UPDATE SET 
      purpose_group = EXCLUDED.purpose_group,
      purpose_label = EXCLUDED.purpose_label,
      category = EXCLUDED.category,
      required_contract_type = EXCLUDED.required_contract_type,
      default_document_type = EXCLUDED.default_document_type,
      sort_order = EXCLUDED.sort_order;

INSERT INTO workflow_settings (issue_type_name, document_prefix) VALUES 
      ('license_master', 'LIC'),
      ('lic_individual', 'ILT'),
      ('manufacturing', 'ROY'),
      ('outsourcing', 'OUT'),
      ('purchase_order', 'PO'),
      ('delivery_inspec', 'INS'),
      ('payment', 'PAY'),
      ('sales_master', 'SAL'),
      ('legal_consult', 'REQ'),
      ('nda', 'NDA')
    ON CONFLICT (issue_type_name) DO UPDATE SET document_prefix = EXCLUDED.document_prefix;

UPDATE documents
        SET form_data = CASE
          WHEN form_data ? 'BREACH_CURE_DAYS'
            THEN form_data - 'CURE_PERIOD_DAYS'
          ELSE (form_data - 'CURE_PERIOD_DAYS')
               || jsonb_build_object('BREACH_CURE_DAYS', form_data->'CURE_PERIOD_DAYS')
        END
      WHERE template_type = 'sales_master_buyer'
        AND form_data ? 'CURE_PERIOD_DAYS';

CREATE INDEX IF NOT EXISTS idx_document_drafts_issue
       ON document_drafts(issue_key);
